#!/usr/bin/env python3
"""
Converts loader.html into a C header (loader_html.h) for embedding in ESP32 firmware.
Run from the repo root: python3 tools/generate_loader_h.py
"""
import gzip, os, sys

src  = os.path.join(os.path.dirname(__file__), '..', 'loader.html')
out  = os.path.join(os.path.dirname(__file__), '..', 'firmware', 'loader_html.h')

os.makedirs(os.path.dirname(out), exist_ok=True)

with open(src, 'rb') as f:
    raw = f.read()

compressed = gzip.compress(raw, compresslevel=9)

hex_lines = []
for i in range(0, len(compressed), 16):
    chunk = compressed[i:i+16]
    hex_lines.append('  ' + ', '.join(f'0x{b:02x}' for b in chunk))

hex_body = ',\n'.join(hex_lines)

header = f"""\
#pragma once
#include <pgmspace.h>

// Auto-generated by tools/generate_loader_h.py — do not edit manually.
// Source: loader.html ({len(raw)} bytes uncompressed, {len(compressed)} bytes gzipped)

static const uint8_t LOADER_HTML_GZ[] PROGMEM = {{
{hex_body}
}};
static const size_t LOADER_HTML_GZ_LEN = {len(compressed)};

/*
  Usage in firmware (ESPAsyncWebServer):

  #include "loader_html.h"

  server.on("/loader", HTTP_GET, [](AsyncWebServerRequest *req) {{
    AsyncWebServerResponse *res = req->beginResponse_P(
      200, "text/html", LOADER_HTML_GZ, LOADER_HTML_GZ_LEN);
    res->addHeader("Content-Encoding", "gzip");
    req->send(res);
  }});

  // OTA firmware endpoint
  server.on("/update/firmware", HTTP_POST,
    [](AsyncWebServerRequest *req) {{
      req->send(200, "text/plain", Update.hasError() ? "FAIL" : "OK");
      if (!Update.hasError()) ESP.restart();
    }},
    [](AsyncWebServerRequest *req, String filename, size_t index, uint8_t *data, size_t len, bool final) {{
      if (!index) Update.begin(UPDATE_SIZE_UNKNOWN, U_FLASH);
      Update.write(data, len);
      if (final) Update.end(true);
    }}
  );

  // OTA filesystem endpoint
  server.on("/update/filesystem", HTTP_POST,
    [](AsyncWebServerRequest *req) {{
      req->send(200, "text/plain", Update.hasError() ? "FAIL" : "OK");
      if (!Update.hasError()) ESP.restart();
    }},
    [](AsyncWebServerRequest *req, String filename, size_t index, uint8_t *data, size_t len, bool final) {{
      if (!index) {{
        LittleFS.end();
        Update.begin(UPDATE_SIZE_UNKNOWN, U_SPIFFS);
      }}
      Update.write(data, len);
      if (final) {{
        Update.end(true);
        LittleFS.begin();
      }}
    }}
  );
*/
"""

with open(out, 'w') as f:
    f.write(header)

print(f"Generated {out}")
print(f"  loader.html:  {len(raw):,} bytes")
print(f"  gzipped:      {len(compressed):,} bytes ({100 - len(compressed)*100//len(raw)}% smaller)")
